apiVersion: v1
kind: Secret
metadata:
  name: smart-charity-backend-secret
type: Opaque
stringData:
  # KETIK STRING KONEKSI MONGODB ATLAS ANDA DI SINI.
  # Pastikan URL sudah di-encode jika ada karakter khusus.
  MONGODB_URI: "mongodb+srv://<USERNAME>:<PASSWORD>@cluster.mongodb.net/db?retryWrites=true&w=majority"